"""initial

Revision ID: 931a32a81fd3
Revises: 
Create Date: 2026-02-14 21:43:55.914346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector as PGVECTOR

# revision identifiers, used by Alembic.
revision: str = '931a32a81fd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clusters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('centroid', PGVECTOR(dim=3072), nullable=True),
    sa.Column('expansion_triggered', sa.Boolean(), nullable=False),
    sa.Column('expansion_query', sa.Text(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clusters'))
    )
    op.create_index('idx_cluster_article_count', 'clusters', [sa.literal_column('article_count DESC')], unique=False)
    op.create_index('idx_cluster_category', 'clusters', ['category'], unique=False)
    op.create_index('idx_cluster_updated', 'clusters', [sa.literal_column('last_updated_at DESC')], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_discovered', sa.Integer(), nullable=False),
    sa.Column('articles_processed', sa.Integer(), nullable=False),
    sa.Column('articles_failed', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_runs'))
    )
    op.create_index('idx_pipeline_run_started', 'pipeline_runs', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index('idx_pipeline_run_status', 'pipeline_runs', ['status'], unique=False)
    op.create_table('rss_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('fetch_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rss_sources')),
    sa.UniqueConstraint('url', name=op.f('uq_rss_sources_url'))
    )
    op.create_index('idx_rss_source_category', 'rss_sources', ['category'], unique=False)
    op.create_index('idx_rss_source_enabled', 'rss_sources', ['enabled'], unique=False)
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('original_title', sa.String(length=500), nullable=True),
    sa.Column('original_content', sa.Text(), nullable=True),
    sa.Column('original_image_url', sa.Text(), nullable=True),
    sa.Column('firecrawl_title', sa.String(length=500), nullable=True),
    sa.Column('firecrawl_content', sa.Text(), nullable=True),
    sa.Column('iframely_title', sa.String(length=500), nullable=True),
    sa.Column('iframely_content', sa.Text(), nullable=True),
    sa.Column('iframely_image_url', sa.Text(), nullable=True),
    sa.Column('gemini_title', sa.String(length=500), nullable=True),
    sa.Column('gemini_content', sa.Text(), nullable=True),
    sa.Column('final_title', sa.String(length=500), nullable=False),
    sa.Column('final_content', sa.Text(), nullable=False),
    sa.Column('final_image_url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], name=op.f('fk_articles_cluster_id_clusters')),
    sa.ForeignKeyConstraint(['source_id'], ['rss_sources.id'], name=op.f('fk_articles_source_id_rss_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_articles')),
    sa.UniqueConstraint('original_url', name=op.f('uq_articles_original_url'))
    )
    op.create_index('idx_article_cluster', 'articles', ['cluster_id'], unique=False)
    op.create_index('idx_article_created', 'articles', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_article_published', 'articles', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_article_source', 'articles', ['source_id'], unique=False)
    op.create_index('idx_article_status', 'articles', ['status'], unique=False)
    op.create_table('gravity_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('industry_impact', sa.Float(), nullable=False),
    sa.Column('consumer_impact', sa.Float(), nullable=False),
    sa.Column('actionability', sa.Float(), nullable=False),
    sa.Column('risk_urgency', sa.Float(), nullable=False),
    sa.Column('novelty', sa.Float(), nullable=False),
    sa.Column('technical_depth', sa.Float(), nullable=False),
    sa.Column('second_order_potential', sa.Float(), nullable=False),
    sa.Column('builder_relevance', sa.Float(), nullable=False),
    sa.Column('entertainment_value', sa.Float(), nullable=False),
    sa.Column('signal_to_noise', sa.Float(), nullable=False),
    sa.Column('viral_potential', sa.Float(), nullable=False),
    sa.Column('early_trend_signal', sa.Float(), nullable=False),
    sa.Column('pr_fluff', sa.Float(), nullable=False),
    sa.Column('speculation', sa.Float(), nullable=False),
    sa.Column('concreteness', sa.Float(), nullable=False),
    sa.Column('paid_sponsorship', sa.Float(), nullable=False),
    sa.Column('editorial_vote', sa.String(length=20), nullable=False),
    sa.Column('novelty_gate', sa.Boolean(), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('scoring_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_gravity_scores_article_id_articles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gravity_scores')),
    sa.UniqueConstraint('article_id', name=op.f('uq_gravity_scores_article_id'))
    )
    op.create_index('idx_gravity_composite', 'gravity_scores', [sa.literal_column('composite_score DESC')], unique=False)
    op.create_index('idx_gravity_editorial_vote', 'gravity_scores', ['editorial_vote'], unique=False)
    op.create_index('idx_gravity_novelty_gate', 'gravity_scores', ['novelty_gate'], unique=False)
    op.create_table('pipeline_step_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=True),
    sa.Column('step_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_pipeline_step_logs_article_id_articles')),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], name=op.f('fk_pipeline_step_logs_pipeline_run_id_pipeline_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_step_logs'))
    )
    op.create_index('idx_step_log_article', 'pipeline_step_logs', ['article_id'], unique=False)
    op.create_index('idx_step_log_run', 'pipeline_step_logs', ['pipeline_run_id'], unique=False)
    op.create_index('idx_step_log_step_status', 'pipeline_step_logs', ['step_name', 'status'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('human_tldr', sa.String(length=300), nullable=False),
    sa.Column('vector_tldr', sa.Text(), nullable=False),
    sa.Column('key_points', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rewritten_title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('generation_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_summaries_article_id_articles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summaries')),
    sa.UniqueConstraint('article_id', name=op.f('uq_summaries_article_id'))
    )
    op.create_index('idx_summary_category', 'summaries', ['category'], unique=False)
    op.create_table('vectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('embedding', PGVECTOR(dim=3072), nullable=True),
    sa.Column('model_used', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('fk_vectors_article_id_articles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vectors')),
    sa.UniqueConstraint('article_id', name=op.f('uq_vectors_article_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vectors')
    op.drop_index('idx_summary_category', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index('idx_step_log_step_status', table_name='pipeline_step_logs')
    op.drop_index('idx_step_log_run', table_name='pipeline_step_logs')
    op.drop_index('idx_step_log_article', table_name='pipeline_step_logs')
    op.drop_table('pipeline_step_logs')
    op.drop_index('idx_gravity_novelty_gate', table_name='gravity_scores')
    op.drop_index('idx_gravity_editorial_vote', table_name='gravity_scores')
    op.drop_index('idx_gravity_composite', table_name='gravity_scores')
    op.drop_table('gravity_scores')
    op.drop_index('idx_article_status', table_name='articles')
    op.drop_index('idx_article_source', table_name='articles')
    op.drop_index('idx_article_published', table_name='articles')
    op.drop_index('idx_article_created', table_name='articles')
    op.drop_index('idx_article_cluster', table_name='articles')
    op.drop_table('articles')
    op.drop_index('idx_rss_source_enabled', table_name='rss_sources')
    op.drop_index('idx_rss_source_category', table_name='rss_sources')
    op.drop_table('rss_sources')
    op.drop_index('idx_pipeline_run_status', table_name='pipeline_runs')
    op.drop_index('idx_pipeline_run_started', table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index('idx_cluster_updated', table_name='clusters')
    op.drop_index('idx_cluster_category', table_name='clusters')
    op.drop_index('idx_cluster_article_count', table_name='clusters')
    op.drop_table('clusters')
    # ### end Alembic commands ###
